name: Generate and Release

on:
  push:
    branches:
      - main

jobs:
  build-lib:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [23.11]
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CASE_SSH_PRIVATE_KEY }}
      - uses: cachix/install-nix-action@v23
        with:
          install_url: https://releases.nixos.org/nix/nix-2.20.3/install
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v9
      
      - uses: actions/checkout@v4
        with:
          repository: hytech-racing/HT_params
          ref: refs/heads/main
          
      - run: nix run .#nanopb-runner

      - name: Get current date and time
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H_%M_%S')"

      - name: create release artifact
        run: |
          mkdir -p ht_eth_pb_lib
          mv default_config.h ht_eth_pb_lib
          mv ht_eth.pb.* ht_eth_pb_lib
          echo -e "{\n\"name\": \"ht_eth_pb_lib\",\n\"version\": \"1.${{ github.run_number }}.0\"\n}" >> ht_eth_pb_lib/library.json
          tar -czvf ht_eth_pb_lib.tar.gz ht_eth_pb_lib
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.date.outputs.date }}
          files: |
            ht_eth_pb_lib.tar.gz
            ht_eth.proto


